-- Makes the quiz and progress bar on the e-learning page real.
-- Previously: the quiz was one hardcoded question with only one working
-- button (the other did nothing and always "passed"); progress was a
-- slider the learner dragged themselves, saved only to their own
-- localStorage — neither reflected anything real or was shared across
-- devices.

-- Real, admin-authored quiz per formation. Shape: a JSON array of
-- { "question": string, "options": string[], "correct": number }.
alter table public.formations add column if not exists quiz jsonb;

-- Tracks real per-learner progress per formation: whether the video was
-- actually watched (via the YouTube IFrame API, not self-reported) and
-- whether the quiz was actually passed.
create table if not exists public.learning_progress (
  id bigint generated by default as identity primary key,
  formation_id text not null references public.formations(id) on delete cascade,
  email text not null,
  video_watched boolean not null default false,
  quiz_passed boolean not null default false,
  quiz_score int,
  updated_at timestamptz not null default now(),
  unique (formation_id, email)
);

alter table public.learning_progress enable row level security;

drop policy if exists "Admins can read all progress" on public.learning_progress;
create policy "Admins can read all progress"
  on public.learning_progress
  for select
  using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'));

drop policy if exists "Learners can read their own progress" on public.learning_progress;
create policy "Learners can read their own progress"
  on public.learning_progress
  for select
  using (lower(email) = lower(coalesce(auth.jwt() ->> 'email', '')));

drop policy if exists "Learners can upsert their own progress" on public.learning_progress;
create policy "Learners can upsert their own progress"
  on public.learning_progress
  for insert
  with check (lower(email) = lower(coalesce(auth.jwt() ->> 'email', '')));

drop policy if exists "Learners can update their own progress" on public.learning_progress;
create policy "Learners can update their own progress"
  on public.learning_progress
  for update
  using (lower(email) = lower(coalesce(auth.jwt() ->> 'email', '')))
  with check (lower(email) = lower(coalesce(auth.jwt() ->> 'email', '')));
