-- create_messages.sql
-- Stores messages submitted through the public Contact form (api/contact.js writes
-- here using the Supabase service-role key, which bypasses RLS — so no public INSERT
-- policy is needed; only admins ever read/manage this table directly from the browser).

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  name text,
  email text,
  organisation text,
  subject text,
  topic text,
  message text,
  created_at timestamptz default now()
);

alter table public.messages enable row level security;

drop policy if exists "Admins can manage messages" on public.messages;
create policy "Admins can manage messages"
  on public.messages
  for all
  using (
    exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
  )
  with check (
    exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
  );
