-- Makes the "Salle de cours" (Classroom.jsx) real: persisted, realtime chat
-- scoped per formation, a real participant list (names only, never
-- email/phone), and an admin-schedulable live session link — replacing the
-- previous version, which was a pure UI mock with hardcoded fake data.

-- ============ 1. Real-time discussion, one thread per formation ============

create table if not exists public.classroom_messages (
  id bigint generated by default as identity primary key,
  formation_id text not null references public.formations(id) on delete cascade,
  author_name text not null,
  author_email text not null,
  message text not null,
  created_at timestamptz default now()
);

create index if not exists classroom_messages_formation_id_idx on public.classroom_messages(formation_id);

alter table public.classroom_messages enable row level security;

drop policy if exists "Admins can manage classroom messages" on public.classroom_messages;
create policy "Admins can manage classroom messages"
  on public.classroom_messages
  for all
  using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'))
  with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'));

-- Enrolled learners can read and post in the discussion for a formation
-- they're actually registered for (same registration check used to gate
-- the course page itself).
drop policy if exists "Enrolled learners can read classroom messages" on public.classroom_messages;
create policy "Enrolled learners can read classroom messages"
  on public.classroom_messages
  for select
  using (
    exists (
      select 1 from public.registrations r
      where r.formation_id = classroom_messages.formation_id
        and lower(r.email) = lower(coalesce(auth.jwt() ->> 'email', ''))
    )
  );

drop policy if exists "Enrolled learners can post classroom messages" on public.classroom_messages;
create policy "Enrolled learners can post classroom messages"
  on public.classroom_messages
  for insert
  with check (
    lower(author_email) = lower(coalesce(auth.jwt() ->> 'email', ''))
    and exists (
      select 1 from public.registrations r
      where r.formation_id = classroom_messages.formation_id
        and lower(r.email) = lower(coalesce(auth.jwt() ->> 'email', ''))
    )
  );

alter publication supabase_realtime add table public.classroom_messages;

-- ============ 2. Participant names only — never email/phone ============
-- registrations.SELECT is intentionally locked to admin-or-own-row (see
-- sql/allow_learner_read_own_registrations.sql) — a plain view would still
-- run under the caller's own row security, so co-enrolled classmates would
-- stay invisible. This function runs as its owner (security definer) and
-- re-implements the "also enrolled in this formation" check itself, only
-- ever returning names, never contact details.
create or replace function public.classroom_participant_names(p_formation_id text)
returns table(name text)
language sql
security definer
set search_path = public
stable
as $$
  select r.name
  from public.registrations r
  where r.formation_id = p_formation_id
    and exists (
      select 1 from public.registrations mine
      where mine.formation_id = p_formation_id
        and lower(mine.email) = lower(coalesce(auth.jwt() ->> 'email', ''))
    )
  order by r.created_at asc;
$$;

grant execute on function public.classroom_participant_names(text) to authenticated;

-- ============ 3. Admin-schedulable live session ============

alter table public.formations add column if not exists live_session_at timestamptz;
alter table public.formations add column if not exists live_session_url text;
